### ISSUE TITLE
ERROR! Fabric Docker image version of 1.4.7 does not match the versions supported by the test network.

### ISSUE THREAD

**Issue by longtran84** [ialberquilla/hlf2-network#2]
ERROR! Fabric Docker image version of 1.4.7 does not match the versions supported by the test network.

**Comment by ialberquilla** [comment]
You are using the 1.4.7 hyperledger docker version, as your logs shows. Update your docker images as show here: https://hyperledger-fabric.readthedocs.io/en/release-2.0/install.html
Specifiying the version 2
